# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        types: [file]  # override `types: [json]`
        files: \.(json|ipynb)$
  - repo: https://github.com/psf/black
    rev: "24.1.1"
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder-python-imports
    rev: "v3.12.0"
    hooks:
    -   id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
    - id: sphinx-lint
      args: [--jobs=1]
      types: [rst]
